#!/usr/bin/env python3
import click
from pywren_ibm_cloud.runtime.deployutil import create_runtime, clone_runtime, update_runtime, deploy_default_rutime


@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx):
    if ctx.invoked_subcommand is None:
        deploy_default_rutime()


@cli.command('create')
@click.argument('image_name')
def create(image_name):
    create_runtime(image_name)


@cli.command('clone')
@click.argument('image_name')
def clone(image_name):
    clone_runtime(image_name)


@cli.command('update')
@click.argument('image_name')
def update(image_name):
    update_runtime(image_name)


if __name__ == "__main__":
    cli()
