#!/usr/bin/env python3
from pywren_ibm_cloud.runtime import create_runtime, clone_runtime, update_all_runtimes, deploy_default_runtime
import click


@click.group(invoke_without_command=True)
@click.pass_context
@click.option('--memory', default=None, help='memory used by the runtime', type=int)
def cli(ctx, memory):
    if ctx.invoked_subcommand is None:
        deploy_default_runtime(memory=memory)


@cli.command('create')
@click.argument('image_name')
@click.option('--memory', default=None, help='memory used by the runtime', type=int)
def create(image_name, memory):
    create_runtime(image_name, memory=memory)


@cli.command('clone')
@click.argument('image_name')
@click.option('--memory', default=None, help='memory used by the runtime', type=int)
def clone(image_name, memory):
    clone_runtime(image_name, memory=memory)


@cli.command('update')
def update():
    update_all_runtimes()


if __name__ == "__main__":
    cli()
