#!/usr/bin/env python3
import re
import sys

from pywren_ibm_cloud.runtime.cli import cli

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
