# Minimal Docker image for Lithops

FROM python:3.8-slim-buster

ENV FLASK_PROXY_PORT 8080

RUN pip install --upgrade pip setuptools six \
    && pip install --no-cache-dir \
        simplejson \
        httplib2 \
        kafka_python \
        lxml \
        python-dateutil \
        pika==0.13.1 \
        flask \
        gevent \
        ibm-cos-sdk \
        redis \
        requests \
        pandas \
        numpy \
        cloudpickle \
        ps-mem \
        tblib \
        namegenerator

# create action working directory
RUN mkdir -p /action \
    && mkdir -p /actionProxy \
    && mkdir -p /pythonAction

ADD https://raw.githubusercontent.com/apache/openwhisk-runtime-docker/8b2e205c39d84ed5ede6b1b08cccf314a2b13105/core/actionProxy/actionproxy.py /actionProxy/actionproxy.py
ADD pythonrunner.py /pythonAction/pythonrunner.py

CMD ["/bin/bash", "-c", "cd /pythonAction && python -u pythonrunner.py"]
