from pywren_ibm_cloud.compute.runtime.deploy_utils import create_runtime
from pywren_ibm_cloud.compute.runtime.deploy_utils import build_runtime
from pywren_ibm_cloud.compute.runtime.deploy_utils import update_runtime
from pywren_ibm_cloud.compute.runtime.deploy_utils import delete_runtime
from pywren_ibm_cloud.compute.runtime.deploy_utils import clean_runtimes

from pywren_ibm_cloud.compute.runtime.runtime import select_runtime
