name: Tests all OS

on:
  workflow_dispatch:

jobs:
  localhost_tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v5

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '7.x'

      - name: Install Lithops
        run: |
          pip3 install -U .[tests]

      - name: Create Lithops config file
        run: |
          mkdir -p $HOME/.lithops
          echo "lithops:" >> $HOME/.lithops/config
          echo "    monitoring_interval: 0.1" >> $HOME/.lithops/config
          echo "    log_level: DEBUG" >> $HOME/.lithops/config
          echo "    include_modules: None" >> $HOME/.lithops/config
          echo "localhost:" >> $HOME/.lithops/config
          echo "    version: 2" >> $HOME/.lithops/config

      - name: Run Lithops tests
        run: |
          cd lithops/tests
          pytest -v --durations=0 --timeout=120 --timeout-method=thread --backend localhost --storage localhost

      - name: Display last 500 lines of the Lithops log file
        if: cancelled() || failure()
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            tail -n 500 /tmp/lithops-runner/localhost-runner.log
          elif [ "$RUNNER_OS" == "macOS" ]; then
            tail -n 500 $TMPDIR/lithops-runner/localhost-runner.log
          elif [ "$RUNNER_OS" == "Windows" ]; then
            tail -n 500 "C:\Users\RUNNER~1\AppData\Local\Temp\lithops-root\localhost-runner.log"
          fi
